### ISSUE TITLE
Stuck can't start the plugin (see Image)

### ISSUE THREAD

**Issue by muhammadaldan** [strapi-community/strapi-plugin-rest-cache#79]
Hello, this is why every time I run npm run start or develop package it's stuck here (see image) , if i changed it to memory it running well 

<img width="945" alt="image" src="https://github.com/strapi-community/strapi-plugin-rest-cache/assets/49355191/2e08e8c4-02ab-4260-b142-cb452519416f">

> package.json

    "strapi-plugin-redis": "^1.0.1",

    "strapi-plugin-rest-cache": "^4.2.7",

    "strapi-provider-rest-cache-redis": "^4.2.7"

> plugin.js
```js
function getPlugins(env) {
  let redisConfig = {
    config: {
      connections: {
        default: {
          connection: {
            host: env("REDIS_CLUSTER_HOST_1"),
            name: "test",
            db: 0,
          },
          settings: {
            debug: Boolean(env("REDIS_CONNECTION_DEBUG")),
          },
        },
      },
    },
  };
  if (env("NODE_ENV") === "production") {
    // Create a Redis cluster client
    let redisClusterUrls = env("REDIS_CLUSTER_HOST_URLS")
      .split(",")
      .map((url) => {
        return {
          host: url,
          port: 6379,
        };
      });
    redisConfig = {
      config: {
        connections: {
          default: {
            connection: {
              nodes: redisClusterUrls,
              name: "test",
              db: 0,
            },
            settings: {
              debug: Boolean(env("REDIS_CONNECTION_DEBUG")),
            },
          },
        },
      },
    };
  }
  return {
    redis: redisConfig,
    "rest-cache": {
      config: {
        provider: {
          name: "redis",
          options: {
            max: 32767,
            connection: "default",
          },
        },
        strategy: {
          keyPrefix: "test",
          // if you are using keyPrefix for your Redis, please add <keysPrefix>
          contentTypes: [
            // list of Content-Types UID to cache
            "api::city.city",
            // "api::community.community",
            "api::competition.competition",
            "api::competition-type.competition-type",
            "api::division.division",
            // "api::match.match",
            "api::match-event.match-event",
            "api::match-lineup.match-lineup",
            "api::match-statistic.match-statistic",
            "api::player.player",
            "api::season.season",
            "api::sponsor.sponsor",
            // "api::stadium.stadium",
            // "api::team.team",
          ],
          debug: Boolean(env("REDIS_STRATEGY_DEBUG")),
          hitpass: false,
          enableXCacheHeaders: true,
        },
      },
    },
    ckeditor: {
      enabled: true,
      config: {
        editor: {
          mediaEmbed: {
            previewsInData: true,
          },
        },
      },
    },
    seo: {
      enabled: true,
    },
    sentry: {
      enabled: true,
      config: {
        // Only set `dsn` property in production
        dsn: env("NODE_ENV") === "production" ? env("SENTRY_DSN") : null,
      },
    },
  };
}
module.exports = ({ env }) => {
  let commonPlugins = getPlugins(env);
  if (env("NODE_ENV") !== "development") {
    commonPlugins = {
      ...commonPlugins,
      upload: {
        config: {
          provider: "aws-s3",
          providerOptions: {
            s3Options: {
              credentials: {
                accessKeyId: env("AWS_ACCESS_KEY_ID"),
                secretAccessKey: env("AWS_ACCESS_SECRET"),
              },
              region: env("AWS_REGION"),
              params: {
                Bucket: env("AWS_BUCKET_NAME"),
              },
            },
          },
          actionOptions: {
            upload: {},
            uploadStream: {},
            delete: {},
          },
        },
      },
    };
  }
  return commonPlugins;
};
```

**Comment by cezarsmpio** [comment]
Same happening to me, this is how my config looks like:

```ts
export default ({ env }) => ({
  email: {
    config: {
      provider: "strapi-provider-email-resend",
      providerOptions: {
        apiKey: env("RESEND_API_KEY", ""),
      },
      settings: {
        defaultFrom: "redacted",
        defaultReplyTo: "redacted",
      },
    },
  },

  upload: {
    config: {
      provider: "strapi-provider-cloudflare-r2",
      providerOptions: {
        accessKeyId: env("CF_ACCESS_KEY_ID"),
        secretAccessKey: env("CF_ACCESS_SECRET"),
        endpoint: env("CF_ENDPOINT"),
        params: {
          Bucket: env("CF_BUCKET"),
        },
        cloudflarePublicAccessUrl: env("CF_PUBLIC_ACCESS_URL"),
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },

  sentry: {
    enabled: env("NODE_ENV") === "production",
    config: {
      dsn: env("SENTRY_DSN"),
      sendMetadata: true,
    },
  },

  redis: {
    enabled: true,
    config: {
      connections: {
        default: {
          connection: {
            host: env("REDIS_HOST"),
            port: env.int("REDIS_PORT"),
            password: env("REDIS_PASSWORD"),
            db: 0,
          },
          settings: {
            debug: true,
          },
        },
      },
    },
  },

  "rest-cache": {
    enabled: true,
    config: {
      provider: {
        name: "redis",
        options: {
          max: 32767,
          connection: "default",
        },
      },
      strategy: {
        enableEtagSupport: true,
        logs: true,
        clearRelatedCache: true,
        maxAge: 3600000,
        debug: true,
        contentTypes: [
          "api::changelog.changelog"
        ],
      },
    },
  },
});
```

**Comment by derrickmehaffy** [comment]
Can you try upgrading the Redis plugin to 1.1.0 as I just published a new version that changes when the Redis plugin initalizes

**Comment by cezarsmpio** [comment]
Hey @derrickmehaffy, I've been using `^1.1.0` and I'm also having the issue, this is the debug:

```
⠋ Loading Strapi  strapi:strapi-plugin-rest-cache [STRATEGY]: CachePluginStrategy {
  strapi:strapi-plugin-rest-cache   debug: true,
  strapi:strapi-plugin-rest-cache   enableEtag: false,
  strapi:strapi-plugin-rest-cache   enableXCacheHeaders: false,
  strapi:strapi-plugin-rest-cache   enableAdminCTBMiddleware: true,
  strapi:strapi-plugin-rest-cache   resetOnStartup: false,
  strapi:strapi-plugin-rest-cache   clearRelatedCache: true,
  strapi:strapi-plugin-rest-cache   maxAge: 3600000,
  strapi:strapi-plugin-rest-cache   keysPrefix: '',
  strapi:strapi-plugin-rest-cache   contentTypes: [
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: [Function: hitpass],
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::changelog.changelog',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: [Function: hitpass],
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::i18n-desktop-app.i18n-desktop-app',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: [Function: hitpass],
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::i18n-mobile-app.i18n-mobile-app',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: [Function: hitpass],
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::i18n-website.i18n-website',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     }
  strapi:strapi-plugin-rest-cache   ],
  strapi:strapi-plugin-rest-cache   keys: CacheKeysConfig { useHeaders: [], useQueryParams: true }
  strapi:strapi-plugin-rest-cache } +0ms
⠼ Loading Strapi
```

It's stuck on `⠼ Loading Strapi` forever.

```
 "strapi-plugin-redis": "^1.1.0",
"strapi-provider-rest-cache-redis": "^4.2.8",
"strapi-plugin-rest-cache": "^4.2.8",
```

**Comment by muhammadaldan** [comment]
Hello @derrickmehaffy , I also tried setting it to version 1.1.0, the issue is still the same, here is the log and this is my json package

```
> dashboard-service@0.1.0 start
> strapi start


   ╭──────────────────────────────────────────────────────────────────────────────╮
   │                                                                              │
   │             A new version of Strapi is available 4.9.1 → 4.19.1              │
   │   Check out the new releases at: https://github.com/strapi/strapi/releases   │
   │                                                                              │
   ╰──────────────────────────────────────────────────────────────────────────────╯

  strapi:strapi-plugin-rest-cache [STRATEGY]: CachePluginStrategy {
  strapi:strapi-plugin-rest-cache   debug: true,
  strapi:strapi-plugin-rest-cache   enableEtag: false,
  strapi:strapi-plugin-rest-cache   enableXCacheHeaders: true,
  strapi:strapi-plugin-rest-cache   enableAdminCTBMiddleware: true,
  strapi:strapi-plugin-rest-cache   resetOnStartup: false,
  strapi:strapi-plugin-rest-cache   clearRelatedCache: true,
  strapi:strapi-plugin-rest-cache   maxAge: 3600000,
  strapi:strapi-plugin-rest-cache   keysPrefix: '',
  strapi:strapi-plugin-rest-cache   contentTypes: [
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::city.city',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::competition.competition',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::competition-type.competition-type',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::division.division',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::match-event.match-event',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::match-lineup.match-lineup',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::match-statistic.match-statistic',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::player.player',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::season.season',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     },
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: false,
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::sponsor.sponsor',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     }
  strapi:strapi-plugin-rest-cache   ],
  strapi:strapi-plugin-rest-cache   keys: CacheKeysConfig { useHeaders: [], useQueryParams: true }
  strapi:strapi-plugin-rest-cache } +0ms
```

> package.json
```
{
  "name": "dashboard-service",
  "version": "0.1.0",
  "private": true,
  "description": "A Strapi application",
  "license": "MIT",
  "author": {
    "name": "A Strapi developer"
  },
  "scripts": {
    "build": "strapi build",
    "develop": "strapi develop",
    "start": "strapi start",
    "start:cron": "node cron-task.js",
    "strapi": "strapi"
  },
  "dependencies": {
    "@ckeditor/strapi-plugin-ckeditor": "^0.0.5",
    "@strapi/plugin-i18n": "4.9.1",
    "@strapi/plugin-sentry": "^4.6.0",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "4.9.1",
    "@strapi/provider-upload-aws-s3": "^4.5.3",
    "@strapi/strapi": "4.9.1",
    "amqplib": "^0.10.3",
    "axios": "^1.5.0",
    "firebase-admin": "^11.11.0",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.43",
    "node-cron": "^3.0.2",
    "path": "^0.12.7",
    "pg": "^8.8.0",
    "pino": "^8.15.1",
    "pino-pretty": "^10.2.0",
    "qs": "^6.11.2",
    "slugify": "^1.6.6",
    "strapi-plugin-preview-button": "^1.0.1",
    "strapi-plugin-redis": "^1.1.0",
    "strapi-plugin-rest-cache": "^4.2.7",
    "strapi-provider-rest-cache-redis": "^4.2.7"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "strapi": {
    "uuid": "bae11e46-8f00-4048-a4d5-0dc0f3a28d19"
  }
}
```

**Comment by joepValvest** [comment]
Experiencing the same issue, with a local redis server as well as with a remote Railway.app server on the latest version.

**Comment by muhammadaldan** [comment]
fix by remove ^ in package.json 
node version v18.18.2

```json
    "strapi-plugin-redis": "1.0.1",
    "strapi-plugin-rest-cache": "4.2.8",
    "strapi-provider-rest-cache-redis": "4.2.8"
```

**Comment by cezarsmpio** [comment]
Hey @muhammadaldan, this is not really a fix but a workaround. Could you reopen the issue, please?

**Comment by cole20444** [comment]
experiencing the same thing.  I manually walked through the plugin and found that it breaks in the waitForRedis function in lib/index.js.  At the bottom of this function it sets` client.once("ready", onReady)`.  This nor the onError function never get called.  I tested just adding a client.status === 'ready' check and then just calling onReady() and Strapi loaded just fine.  The plugin as expected after that.   Of course this isn't a viable fix but just what i found while investigating:

`function waitForRedis(client) {
  return new Promise((resolve, reject) => {
    const onReady = () => {
      strapi.log.info('REST Cache provider "redis": connection established');

      // eslint-disable-next-line no-use-before-define
      client.off("error", onError);
      resolve();
    };
    const onError = (error) => {
      client.off("ready", onReady);
      reject(
        new Error(
          `Could not initialize REST Cache provider "redis": ${error?.message}`
        )
      );
    };

    client.once("ready", onReady);
    client.once("error", onError);
  });
}`

**Comment by derrickmehaffy** [comment]
Can you upgrade the redis package to v1.1.0 (not 1.0.1) I changed the Redis plugin to start building the redis connections in register rather than bootstrap so that Redis will start before any other plugins

**Comment by cezarsmpio** [comment]
Hi @derrickmehaffy I mentioned here https://github.com/strapi-community/strapi-plugin-rest-cache/issues/79#issuecomment-1924849622 that I'm using `^1.1.0` since the beginning and it didn't work.

Downgrading to `1.0.1` unblocked me.

**Comment by derrickmehaffy** [comment]
hmmmmm, if you use `yarn strapi console` and use the exec shell to type `strapi.redis` and hit enter what data does it give you?

(seeing if the connections exist and are established)

**Comment by derrickmehaffy** [comment]
I was just testing Redis + Cache and I can't reproduce any of this:

![image](https://github.com/strapi-community/strapi-plugin-rest-cache/assets/8593673/aaa7f6b9-2409-4dd1-8435-f12ab74bc649)
![image](https://github.com/strapi-community/strapi-plugin-rest-cache/assets/8593673/80d130f8-53e0-4576-a895-3f7866de0afa)
![image](https://github.com/strapi-community/strapi-plugin-rest-cache/assets/8593673/da314f60-8068-4e39-aa9f-4b1b4a326ae5)

**Comment by cole20444** [comment]
updating to match as much of your setup as i can and rebuilding.

**Comment by cole20444** [comment]
Yeah still a no go.  Node v18.18.0.  Below is my setup.  If the only change I make is updating the strapi-plugin-redis to 1.1.0.  Strapi will not load.  One thing i haven't tested is if this is isolated to remote redis servers.  I don't have redis running locally.  I have an instance running in azure that im connecting to.  

<img width="438" alt="Screenshot 2024-02-09 at 12 28 20 PM" src="https://github.com/strapi-community/strapi-plugin-rest-cache/assets/1178596/65c64d91-e851-4871-a3ec-87693be3094a">
<img width="336" alt="Screenshot 2024-02-09 at 12 28 44 PM" src="https://github.com/strapi-community/strapi-plugin-rest-cache/assets/1178596/0969a96d-d043-4961-bcb2-79ffc1f818d0">

**Comment by derrickmehaffy** [comment]
I try installing redis locally and seeing if it can connect there because it could just be that it can't establish a connection to redis

**Comment by BabyDino** [comment]
I have the same issue with a local Redis. We had a perfectly working setup on AWS ECS and suddenly it became stuck after a PR merge (with packages set to `^1.1.0`).

I have tried multiple Redis versions as well with no luck.

Downgrade to 1.0.1 was the workaround.

**Comment by derrickmehaffy** [comment]
Hmmm I'll need more info to see where the problem is because as it stands currently I can't reproduce this.

Nothing has changed except when Redis is loaded and that's not in the cache plugin it's in my Redis plugin and it should be loaded a hell of a lot earlier now.

Can you all reproduce this in a fresh project or just your existing ones?

**Comment by cole20444** [comment]
Alright i was able to get 1.1.0 to work @derrickmehaffy. So yeah i viewed the changelog and didn't see much changed.  The only big change was the renaming of the bootstrap.js file to register.js and then updating the references of that in the server/index.js file.   Basically just reverting that one change.  This fixed the issue and now the redis connects and strapi load successfully.

<img width="294" alt="Screenshot 2024-02-10 at 11 26 25 AM" src="https://github.com/strapi-community/strapi-plugin-rest-cache/assets/1178596/97fc942d-ef43-4a3c-b821-54d151ec4574">
<img width="344" alt="Screenshot 2024-02-10 at 11 26 35 AM" src="https://github.com/strapi-community/strapi-plugin-rest-cache/assets/1178596/f05874cb-8cd3-45ca-8734-5ff0b2555460">

**Comment by cole20444** [comment]
So I've never looked into the inner workings of custom providers and plugins for Strapi, so i'm not sure why it doesn't work when you add the code to the register.js function to load before bootstrap.

**Comment by derrickmehaffy** [comment]
That's the odd thing as it should and does work fine for me.

(For clarity here, I actually work for Strapi)

I needed to move that to register as some plugins get loaded first before Redis does. 

Just out of curiosity is your project typescript?

**Comment by BabyDino** [comment]
For us it is yes, both Typescript and existing project.

**Comment by hussain-mustafa990** [comment]
Same issue for me.

**Comment by Azhrak** [comment]
I ran into the same problem: infinite `Loading Strapi` when starting develop or production.

Did some digging based on @cole20444's findigs and debugged the `strapi-provider-rest-cache-redis\lib\index.js`. I found out that the `onReady()` is not called because the connection is aleady `client.state === "ready"`, so the `"ready"` has been emitted earlier. I assume my register() lifecycle method has less stuff to initialize so the setup is faster and the race condition is met.

The code below shows one way to fix it.

```js
// strapi-provider-rest-cache-redis\lib\index.js: 

function waitForRedis(client) {
  return new Promise((resolve, reject) => { 
  ...
    if (client.status === "ready") {
       return onReady();
    }
    client.once("ready", onReady);
    client.once("error", onError);
  });
};
```

**Comment by vinodmmm** [comment]
> fix by remove ^ in package.json node version v18.18.2
> 
> ```json
>     "strapi-plugin-redis": "1.0.1",
>     "strapi-plugin-rest-cache": "4.2.8",
>     "strapi-provider-rest-cache-redis": "4.2.8"
> ```

For now this has fixed the issue. I've checked it on node version v18.17.1.
